# Generated by Django 3.0 on 2019-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.BigIntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestid', models.BigIntegerField(db_column='GuestID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
                ('employee_employeeid', models.BigIntegerField(blank=True, db_column='Employee_EmployeeID', null=True)),
            ],
            options={
                'db_table': 'guest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelid', models.IntegerField(db_column='HotelID', primary_key=True, serialize=False)),
                ('hotelname', models.CharField(blank=True, db_column='HotelName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotelemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_hotelid', models.IntegerField(blank=True, db_column='Hotel_HotelID', null=True)),
                ('employee_employeeid', models.BigIntegerField(blank=True, db_column='Employee_EmployeeID', null=True)),
            ],
            options={
                'db_table': 'hotelemployee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('promoid', models.BigIntegerField(db_column='PromoID', primary_key=True, serialize=False)),
                ('promocode', models.CharField(blank=True, db_column='PromoCode', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=45, null=True)),
                ('roomtype_roomtypeid', models.SmallIntegerField(blank=True, db_column='RoomType_RoomTypeID', null=True)),
            ],
            options={
                'db_table': 'promo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.BigIntegerField(db_column='ReservationID', primary_key=True, serialize=False)),
                ('guest_guestid', models.BigIntegerField(blank=True, db_column='Guest_GuestID', null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservationdetail',
            fields=[
                ('reservationdetailid', models.BigIntegerField(db_column='ReservationDetailID', primary_key=True, serialize=False)),
                ('reservation_reservationid', models.BigIntegerField(blank=True, db_column='Reservation_ReservationID', null=True)),
                ('roomreservation_roomreservationid', models.BigIntegerField(blank=True, db_column='RoomReservation_RoomReservationID', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=45, null=True)),
            ],
            options={
                'db_table': 'reservationdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservationpromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_promoid', models.BigIntegerField(blank=True, db_column='Promo_PromoID', null=True)),
                ('reservation_reservationid', models.BigIntegerField(blank=True, db_column='Reservation_ReservationID', null=True)),
            ],
            options={
                'db_table': 'reservationpromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.IntegerField(db_column='RoomID', primary_key=True, serialize=False)),
                ('roomtype_roomtypeid', models.SmallIntegerField(blank=True, db_column='RoomType_RoomTypeID', null=True)),
                ('hotel_hotelid', models.IntegerField(blank=True, db_column='Hotel_HotelID', null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomrate',
            fields=[
                ('roomrateid', models.BigIntegerField(db_column='RoomRateID', primary_key=True, serialize=False)),
                ('roomtype_roomtypeid', models.SmallIntegerField(blank=True, db_column='RoomType_RoomTypeID', null=True)),
            ],
            options={
                'db_table': 'roomrate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomreservation',
            fields=[
                ('roomreservationid', models.BigIntegerField(db_column='RoomReservationID', primary_key=True, serialize=False)),
                ('room_roomid', models.IntegerField(blank=True, db_column='Room_RoomID', null=True)),
                ('reservation_reservationid', models.BigIntegerField(blank=True, db_column='Reservation_ReservationID', null=True)),
            ],
            options={
                'db_table': 'roomreservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomreservationguest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_guestid', models.BigIntegerField(blank=True, db_column='Guest_GuestID', null=True)),
                ('roomreservation_roomreservationid', models.BigIntegerField(blank=True, db_column='RoomReservation_RoomReservationID', null=True)),
            ],
            options={
                'db_table': 'roomreservationguest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('roomtypeid', models.SmallIntegerField(db_column='RoomTypeID', primary_key=True, serialize=False)),
                ('roomtype', models.CharField(blank=True, db_column='RoomType', max_length=20, null=True)),
            ],
            options={
                'db_table': 'roomtype',
                'managed': False,
            },
        ),
    ]
