# Generated by Django 2.2.2 on 2019-12-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20191216_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
